# Generated by Django 4.1.7 on 2023-04-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_remove_moderador_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='Moderador',
        ),
    ]
