# Generated by Django 4.1.7 on 2023-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_aviso_delete_moderador'),
    ]

    operations = [
        migrations.AddField(
            model_name='frase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotofrase/'),
        ),
    ]
