# Generated by Django 4.1.7 on 2023-05-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_infoextra_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='frase_descripcion',
            field=models.TextField(blank=True),
        ),
    ]
